swagger: '2.0'
info:
  title: my-api
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /tasks:
    get:
      summary: Tasks
      operationId: taskGet
      x-google-backend:
        address: https://flow-roll-backend-staging-higuif7p5q-uc.a.run.app/tasks
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"